class PlayerConfig:
    PLAYER_SIGN = 'P'
    PLAYER_COLOR = (0, 255, 0)
    COUNT_LIVES = 3
    MAX_COUNT_OF_BOMBS = 3
    MAX_PLAYER_STONE_MOVES = 5
    MAX_PLAYER_JUMPS = 3
    STONE_MOVES = 5
    PLAYER_JUMPS = 3
    SECONDS_TO_RESTORE_STONE_MOVES = 5
    SECONDS_TO_RESTORE_JUMPS = 5
    RESTORE_STONE_MOVES_AT_ONCE = 1
    RESTORE_JUMPS_AT_ONCE = 1
    PLAYER_TO_STRING = "player"